name: Sanity Workflow

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  klint:
    name: Run ktlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Ktlint
        run: bash ./gradlew ktlint --stacktrace

  lint:
    name: Run lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Lint
        id: Lint
        run: bash ./gradlew lint --stacktrace